# Generated by Django 5.2.3 on 2025-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("price", models.PositiveIntegerField()),
                (
                    "color",
                    models.TextField(
                        choices=[
                            ("wild-berry", "Wild Berry"),
                            ("dirty-blue", "Dirty Blue"),
                            ("sage", "Sage"),
                            ("terra-cotta", "Terra Cotta"),
                            ("rodeo-dust", "Rodeo Dust"),
                            ("como-green", "Como Green"),
                            ("grey-goose", "Grey Goose"),
                            ("rose-gold", "Rose Gold"),
                            ("gold", "Gold"),
                            ("black", "Black"),
                            ("cyan", "Cyan"),
                            ("dark-grey", "Dark Grey"),
                            ("carbon-grey", "Carbon Grey"),
                            ("white", "White"),
                            ("soft-antique", "Soft Antique"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("on-sale", "On Sale"), ("in-tock", "In Stock")]
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
