# Generated by Django 5.2.3 on 2025-07-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AddField(
            model_name="items",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="color",
            field=models.CharField(
                choices=[
                    ("wild-berry", "Wild Berry"),
                    ("dirty-blue", "Dirty Blue"),
                    ("sage", "Sage"),
                    ("terra-cotta", "Terra Cotta"),
                    ("rodeo-dust", "Rodeo Dust"),
                    ("como-green", "Como Green"),
                    ("grey-goose", "Grey Goose"),
                    ("rose-gold", "Rose Gold"),
                    ("gold", "Gold"),
                    ("black", "Black"),
                    ("cyan", "Cyan"),
                    ("dark-grey", "Dark Grey"),
                    ("carbon-grey", "Carbon Grey"),
                    ("white", "White"),
                    ("soft-antique", "Soft Antique"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="status",
            field=models.CharField(
                choices=[("on-sale", "On Sale"), ("in-tock", "In Stock")]
            ),
        ),
    ]
