# Generated by Django 5.2.4 on 2025-08-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_itemextraimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='addional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Diamond_Earring', 'Diamond Earring'), ('Chains', 'Chains'), ('Necklaces', 'Necklaces'), ('Diamond_Necklace', 'Diamond Necklace'), ('Diamond_Bracelet', 'Diamond Bracelet'), ('Diamond_Bangles', 'Diamond Bangles '), ('Chokers', 'Chokers ')], default='Diamond_Earring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
