# Generated by Django 5.2.3 on 2025-07-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Items", "0003_itemextraimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquire",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.TextField()),
                ("Message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "items",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="select_items",
                        to="Items.items",
                    ),
                ),
            ],
        ),
    ]
