# Generated by Django 5.2.3 on 2025-07-31 09:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailSender",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "subject",
                    models.CharField(
                        help_text="Emails auto-delete after 40 days.", max_length=255
                    ),
                ),
                ("message", wagtail.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "send_email_now",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to send the email immediately upon saving",
                    ),
                ),
                (
                    "to_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Enter 'To' email addresses separated by commas (e.g., email1@example.com, email2@example.com)",
                    ),
                ),
                (
                    "cc_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Enter 'CC' email addresses separated by commas (e.g., email3@example.com, email4@example.com)",
                    ),
                ),
                (
                    "bcc_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Enter 'BCC' email addresses separated by commas (e.g., email5@example.com, email6@example.com)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailer",
                "verbose_name_plural": "Mailer",
            },
        ),
    ]
