# Generated by Django 5.2.4 on 2025-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='order_placed', max_length=20),
        ),
    ]
